### ISSUE TITLE
Publish on Maven Central

### ISSUE THREAD

**Issue by aSemy** [lgwillmore/warden#29]
Hi, would you be interested in publishing this library on Maven Central? 

I've recently published a Kotlin Multiplatform library so I would be able to help as there are a few 'gotchas'

**Comment by lgwillmore** [comment]
Absolutely.

I have some leave  this week, and I am keen to do a spring clean of the whole project and tackle a bunch of the current issues we have. Work towards a 0.2.0 release.

Current build and publish happens with github actions. if we can get a pull request going that wires up some new actions for publishing to maven that would be great.

**Comment by aSemy** [comment]
Great! I'll make a PR. 

I'll also bump the Gradle version and use buildSrc to share some of the common logic - unless you have strong objections?

**Comment by lgwillmore** [comment]
No objections :D

**Comment by lgwillmore** [comment]
Cool - we have the codes.laurence.warden group id. Need to publish a GPG key still.

If the project actually gets a bit of adoption I will probably move it to its own github organization and register a dedicated domain of some kind.

**Comment by lgwillmore** [comment]
@aSemy thanks for the work you did to get this one started. We are finally available on maven central even if it is a bit late.
